### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by EEAppDev** [KELLERAGfuerDruckmesstechnik/CodeSamplesAndProtocols#1]
Link to Bus Protocols & Communication Protocols as well as C++ Code Samples not working!

**Comment by cBashTN** [comment]
Yes true! Unfortunately, our website admin deleted the all examples yesterday. We are in the very act to restore them.

**Comment by EEAppDev** [comment]
When will it be available again? We are evaluating PAA-33X at our factory and i need to code some serial communication, which is impossible without any documentation or sample.

**Comment by cBashTN** [comment]
I understand your need and I'm sorry for the delay caused by the holiday season.  

Until we fix the links, please download a copy of the examples here:  
- Compiled DLLs  
  [http://www.keller-druck2.ch/swupdate/KELLER_dll/KELLER_dll.zip](http://www.keller-druck2.ch/swupdate/KELLER_dll/KELLER_dll.zip)  
- All bus protocols  
 [http://www.keller-druck2.ch/swupdate/BusProtocols/BusProtocols.zip](http://www.keller-druck2.ch/swupdate/BusProtocols/BusProtocols.zip) 
- C++ examples  
  [http://www.keller-druck2.ch/swupdate/CPP/CPP.zip](http://www.keller-druck2.ch/swupdate/CPP/CPP.zip)

Please tell me which examples you need and I try to find them for you until the links are working again.

**Comment by EEAppDev** [comment]
Perfect. This is all i was looking for. Thanks.
Vielen Dank.

**Comment by cBashTN** [comment]
People are back from holidays. The links are restored again.
